classes:

- system.linux.system.repo.mos9

- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.salt.control.cluster.opencontrail_analytics_cluster
- system.salt.control.cluster.opencontrail_control_cluster
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- cluster.nfv-lab
parameters:
  _param:
    cluster_vip_address: ${_param:infra_compute_address}
    cluster_node01_address: ${_param:infra_compute_node01_address}
    cluster_node02_address: ${_param:infra_compute_node02_address}
    cluster_node03_address: ${_param:infra_compute_node03_address}
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: enp2s0f0
    primary_first_nic: enp2s0f1
    primary_second_nic: enp5s0f0
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.control:
          cpu: 8
          ram: 16384
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 6
          ram: 8192
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 6
          ram: 16384
          disk_profile: small
          net_profile: default
        openstack.telemetry:
          cpu: 6
          ram: 8192
          disk_profile: xxlarge
          net_profile: default
        openstack.proxy:
          cpu: 4
          ram: 4096
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 8
          ram: 16384
          disk_profile: small
          net_profile: opencontrail
        opencontrail.analytics:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: default
        stacklight.log:
          cpu: 4
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
        stacklight.server:
          cpu: 4
          ram: 4096
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 4
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}
  virt:
    nic:
      default:
        - name: eth1
          bridge: br_mgm
        - name: eth0
          bridge: br_ctl
      opencontrail:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
        - name: eth2
          bridge: br_data
          model: virtio
  linux:
    network:
      interface:
        eth0:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
        eth1:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:primary_first_nic}
          master: bond0
        eth2:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:primary_second_nic}
          master: bond0
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: 255.255.255.192
          gateway: 172.16.49.65
          name_servers:
          - 8.8.8.8
          - 8.8.4.4
          use_interfaces:
          - ${_param:deploy_nic}
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ${_param:primary_first_nic}
          - ${_param:primary_second_nic}
          slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
          mode: active-backup
        bond0.2422:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        bond0.2423:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          use_interfaces:
          - bond0.2422
        br_data:
          enabled: true
          type: bridge
          proto: manual
          use_interfaces:
          - bond0.2423
